mixswap/home/urls.py
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns(
    '',
    url(r'^$', views.home, name='home'),
    url(r'^top_favs/$', views.top_favs, name='top_favs'),
)

mixswap/mixswap/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('home:home'))),
    url(r'^home/', include('home.urls', namespace="home")),
    url(r'^mix/', include('mixes.urls', namespace="mixes")),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),
    # Examples:
    # url(r'^$', 'mixswap.views.home', name='home'),
    # url(r'^mixswap/', include('mixswap.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

mixswap/home/models.py
from django.db import models

# Create your models here.

mixswap/home/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from mixes.models import Mix
from django.db.models import Count, Sum, Avg


@login_required
def home(request):
    user = request.user
    user_mixes = Mix.objects.filter(user=user).order_by('-id')
    mixes = Mix.objects.filter(is_published=True).order_by('-date_published')

    return render(
        request,
        'home/home.html',
        {
            'user': user,
            'user_mixes': user_mixes,
            'all_mixes': mixes,
        }
    )


@login_required
def top_favs(request):

    mixes = Mix.objects.annotate(num_favs=Count('mixsong__favourites')).annotate(num_songs=Count('mixsong', distinct=True)).order_by('-num_favs', 'num_songs')[:10]

    return render(
        request,
        'home/top-favs.html',
        {
            'mixes': mixes
        }
    )

mixswap/home/templates/home/home.html
{% extends 'base.html' %}
{% block page_class %}home{% endblock %}

{% block content %}
<h1>mix(s)wap</h1>

<nav>
	<a id="makeNewMixLink" href="javascript:;" data-url="{% url 'mixes:new_mix' %}" class="new-mix-link">Make New Mix</a>
	<a href="{% url 'home:top_favs' %}">Top Favs</a>
	<a href="{% url 'logout' %}">Logout</a>
</nav>
<div class="all-mixes-block">
	<header><h2>All Mixes</h2></header>
	<table class="mix-list-table all-mixes-table">
		{% for mix in all_mixes %}
			<tr class="mix-item">
				<td class="mix-image">{% if mix.picture_file %}<a href="{% url 'mixes:mix' mix.id %}"><img src="{{ mix.picture_file.url }}" alt=""></a>{% endif %}</td>
				<td class="mix-title">
					<a href="{% url 'mixes:mix' mix.id %}" {% if user not in mix.user_listens.all %} class="unheard" {% endif %}>{{ mix.title }}</a>
					<span class="username">{{ mix.user.first_name }} - {{ mix.date_published }}</span>
				</td>
			</tr>
		{% endfor %}
	</table>
</div>

<div class="my-mixes-block">
	<header><h2>My Mixes</h2></header>
	<table class="mix-list-table my-mixes-table">
		{% for mix in user_mixes %}
			<tr class="my-mix-item" id="myMixItem_{{ mix.id }}">
				<td class="mix-title"><a id="myMix_{{ mix.id }}" href="{% url 'mixes:mix' mix.id %}">{{ mix.title }}</a>{% if not mix.is_published %}<span class="unpublished"> (unfinished)</span>{% endif %}</td>
				<td class="delete-mix"><a class="delete-mix-link" href="javascript:;" data-url="{% url 'mixes:delete_mix' mix.id %}" data-id="{{ mix.id }}">X</a></td>
			</tr>
		{% endfor %}
	</table>
</div>


<br class="clear">
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {

        App.init({
        	page:'home'
        });
    });

</script>

{% endblock %}

mixswap/home/templates/home/top-favs.html
{% extends 'base.html' %}
{% block page_class %}home top-favs{% endblock %}

{% block content %}
<h1>mix(s)wap</h1>

<nav>
	<a href="{% url 'home:home' %}">&lt; Home</a>
</nav>

<div class="all-mixes-block">
	<header><h2>Top 10 favourited mixes</h2></header>
	<table class="mix-list-table all-mixes-table">
		{% for mix in mixes %}
			<tr class="mix-item">
				<td class="place-count">{{ forloop.counter }})</td>
				<td class="mix-image">{% if mix.picture_file %}<a href="{% url 'mixes:mix' mix.id %}"><img src="{{ mix.picture_file.url }}" alt=""></a>{% endif %}</td>
				<td class="mix-title">
					<a href="{% url 'mixes:mix' mix.id %}" {% if user not in mix.user_listens.all %} class="unheard" {% endif %}>{{ mix.title }}</a>
					<span class="username">{{ mix.user.first_name }} - {{ mix.date_published }}</span>
				</td>
				<td class="fav-count">{{ mix.num_favs }}</td>
			</tr>
		{% endfor %}
	</table>
</div>

<br class="clear">
{% endblock %}