mixswap/home/urls.py
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns(
    '',
    url(r'^$', views.home, name='home'),
    url(r'^top_favs/$', views.top_favs, name='top_favs'),
)

mixswap/mixes/urls.py
from django.conf.urls import patterns, url

from mixes import views

urlpatterns = patterns(
    '',
    url(r'^(?P<pk>\d+)/$', views.mix, name='mix'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_mix, name='delete_mix'),
    url(r'^(?P<pk>\d+)/upload_picture/$', views.upload_picture, name='upload_picture'),
    url(r'^(?P<pk>\d+)/delete_picture/$', views.delete_picture, name='delete_picture'),
    url(r'^(?P<pk>\d+)/upload_song/$', views.upload_song, name='upload_song'),
    url(r'^(?P<pk>\d+)/update_song_order/$', views.update_song_order, name='update_song_order'),
    url(r'^(?P<pk>\d+)/song/(?P<song_id>\d+)/$', views.update_song, name='update_song'),
    url(r'^(?P<pk>\d+)/comment/$', views.add_comment, name='add_comment'),
    url(r'^(?P<pk>\d+)/download_mix/$', views.download_mix, name='download_mix'),
    url(r'^(?P<pk>\d+)/comments/$', views.get_comments, name='comments'),
    url(r'^new/$', views.new_mix, name='new_mix'),
)

mixswap/mixswap/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('home:home'))),
    url(r'^home/', include('home.urls', namespace="home")),
    url(r'^mix/', include('mixes.urls', namespace="mixes")),
    url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),
    # Examples:
    # url(r'^$', 'mixswap.views.home', name='home'),
    # url(r'^mixswap/', include('mixswap.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

mixswap/mixes/forms.py
from django import forms


class SongForm(forms.Form):
    songfile = forms.FileField(
        label='Select an audio track',
        help_text='max. 50 megabytes'
    )


class PictureForm(forms.Form):
    picfile = forms.ImageField(
        label='Select a picture',
        help_text='max. 5 megabytes'
    )

mixswap/mixes/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.template import Context, loader
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Q
from django.core.servers.basehttp import FileWrapper

import os, json, datetime
import sendgrid, html2text

from mixes.models import Mix, Song, MixSong, Comment
from mixes.forms import PictureForm, SongForm


def get_audio_meta(file):
    file_type = ''
    if (settings.ENVIRONMENT != 'local'):
       # magic_object = magic.Magic()
        mime = magic.from_file(file, mime=True)
        if ('audio/mp4' in mime):
            file_type = 'm4a'
        elif ('audio/mpeg' in mime):
            file_type = 'mp3'
        else:
            file_type = 'unknown'
    else:
        file_type = 'mp3'

    if (file_type == 'mp3'):
        return EasyID3(file)
    elif (file_type == 'm4a'):
        return EasyMP4(file)
    else:
        return False


def jsonResponse(success, response={}):
    
    if (success is False):
        if ('error' not in response):
            response['error'] = 'General error.'
        response['success'] = False
    else:
        response['success'] = True

    return HttpResponse(json.dumps(response), mimetype='application/json')


def send_email(type, *args, **kwargs):
    s = sendgrid.Sendgrid(settings.SENDGRID['username'], settings.SENDGRID['password'], secure=True)

    if (settings.ENVIRONMENT == 'production'):
        email_list = User.objects.filter(~Q(email='')).values_list('email', flat=True)
    else:
        email_list = ["banfangled@yahoo.ca"]

    message_body = ''
    subject = ''
    if (type == 'mix_published'):

        t = loader.get_template('mixes/email/mix-published.html')
        c = Context({
            'user_name': kwargs['user_name'],
            'mix_title': kwargs['mix_title'],
            'mix_id': kwargs['mix_id']
        })
        message_body = t.render(c)
        subject = "New Mix!"

    elif (type == 'comment'):

        t = loader.get_template('mixes/email/comment.html')
        c = Context({
            'user_name': kwargs['user_name'],
            'mix_title': kwargs['mix_title'],
            'mix_id': kwargs['mix_id'],
            'comment': kwargs['comment']
        })
        message_body = t.render(c)
        subject = "Comment on " + kwargs['mix_title']

    if (message_body != ''):
        message = sendgrid.Message("mixmaster@mix-swap.com", subject,  html2text.html2text(message_body), message_body)
        message.add_to(email_list)

        # use the Web API to send your message
        s.web.send(message)


@login_required
def mix(request, pk):
    mix = get_object_or_404(Mix, pk=pk)
    is_user_mix = (mix.user == request.user)
    is_published = mix.is_published

    if (not is_published) and (not is_user_mix):
        raise Http404

    if ('HTTP_X_HTTP_METHOD_OVERRIDE' in request.META):
        data = json.loads(request.body)
        response = {}
        if request.META['HTTP_X_HTTP_METHOD_OVERRIDE'] == 'PATCH':
            if ('title' in data):
                mix.title = data['title']
                mix.save()

                response['title'] = data['title']

            if ('pictureFile' in data):
                delete_picture(request, pk, False)

            if ('isPublished' in data):
                mix.is_published = data['isPublished']
                if (mix.is_published and mix.date_published is None):
                    mix.date_published = datetime.datetime.now()
                mix.save()
                if ('sendEmail' in data):
                    send_email(
                        'mix_published',
                        user_name=request.user.first_name,
                        mix_title=mix.title,
                        mix_id=mix.id
                    )
            
            response['method'] = 'patch'

        return jsonResponse(True, response)

    else:
        picture_form = PictureForm()
        user = request.user
        if (user not in mix.user_listens.all()):
            mix.user_listens.add(user)

        return render(
            request,
            'mixes/mix.html',
            {
                'mix': mix,
                'user': user,
                'mix_songs': MixSong.objects.filter(mix=mix),
                'is_user_mix': is_user_mix,
                'picture_form': picture_form
            }
        )


@login_required
def new_mix(request):
    mix = Mix(
        user=request.user
    )
    mix.save()

    return jsonResponse(True, {'id': mix.id})


@login_required
def delete_mix(request, pk):
    try:
        mix = Mix.objects.get(pk=pk)
    except mix.DoesNotExist:
        return jsonResponse(False, {'error': 'No mix.'})

    if (mix.user != request.user):
        return jsonResponse(False, {'error': 'Bad user.'})

    Song.objects.filter(mix=mix).delete()
    Comment.objects.filter(mix=mix).delete()

    mix.delete()

    return jsonResponse(True)


@login_required
def update_song_order(request, pk):
    try:
        mix = Mix.objects.get(pk=pk, is_published=False)
    except mix.DoesNotExist:
        return jsonResponse(False, {'error': 'No mix.'})

    if (mix.user != request.user):
        return jsonResponse(False, {'error': 'Bad user.'})

    if ('HTTP_X_HTTP_METHOD_OVERRIDE' in request.META):

        data = json.loads(request.body)
        for data_song in data:
            song = Song.objects.get(pk=data_song['id'])
            mix_song = MixSong.objects.get(mix=mix, song=song)
            mix_song.song_order = data_song['songOrder']
            mix_song.save()

        return jsonResponse(True)

    else:
        return jsonResponse(False)


@login_required
def upload_song(request, pk):
    response = {}

    try:
        mix = Mix.objects.get(pk=pk, is_published=False)
    except mix.DoesNotExist:
        return jsonResponse(False, {'error': 'No mix.'})

    if (mix.user != request.user):
        return jsonResponse(False, {'error': 'Bad user.'})

    if request.method == 'POST':
        form = SongForm(request.POST, request.FILES)

        if form.is_valid():

            song_file = request.FILES['songfile']
            song = Song.create({
                'user': request.user,
                'mix': mix,
                'song_file': song_file
            })
            if (song is False):
                return jsonResponse(False, {'error': 'Bad file type.'})
            song.save()

            song_order = mix.songs.count() + 1

            mixSong = MixSong(
                mix=mix,
                song=song,
                song_order=song_order
            )
            mixSong.save()

            response['song_id'] = str(song.id)
            response['title'] = str(song.title)
            response['artist'] = str(song.artist)
            response['song_order'] = str(song_order)
            response['song_file'] = str(song.song_file.url)

        else:
            return jsonResponse(False, {'error': form.errors})

    else:
        return jsonResponse(False, {'error': 'No POST'})

    return jsonResponse(True, response)


@login_required
def update_song(request, pk, song_id):
    try:
        mix = Mix.objects.get(pk=pk)
        song = Song.objects.get(pk=song_id)
    except (mix.DoesNotExist, song.DoesNotExist):
        return jsonResponse(False, {'error': 'No mix or song.'})

    response = {}

    if ('HTTP_X_HTTP_METHOD_OVERRIDE' in request.META):
        if (request.META['HTTP_X_HTTP_METHOD_OVERRIDE'] == 'DELETE'):
            if (mix.user != request.user):
                return jsonResponse(False, {'error': 'Bad user.'})
            
            if (song.song_file):
                os.remove(settings.MEDIA_ROOT + str(song.song_file))
            song.delete()

        elif (request.META['HTTP_X_HTTP_METHOD_OVERRIDE'] == 'PATCH'):
            data = json.loads(request.body)
            if ('isUserFav' in data):
                mix_song = MixSong.objects.get(mix=mix, song=song)
                if (data['isUserFav']):
                    mix_song.favourites.add(request.user)
                else:
                    mix_song.favourites.remove(request.user)
                
                mix_song.save()
                response['total_fav'] = mix_song.favourites.count()

            elif ('title' in data):
                song.title = data['title']
                song.save(update_fields=['title'])

            elif ('artist' in data):
                song.artist = data['artist']
                song.save(update_fields=['artist'])

            return jsonResponse(True, response)

    return jsonResponse(True, {'hey': request.META['HTTP_X_HTTP_METHOD_OVERRIDE']})


@login_required
def upload_picture(request, pk):
    response = {}

    try:
        mix = Mix.objects.get(pk=pk, is_published=False)
    except mix.DoesNotExist:
        return jsonResponse(False, {'error': 'No mix.'})

    if (mix.user != request.user):
        return jsonResponse(False, {'error': 'Bad user.'})

    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES)

        if form.is_valid():
            delete_picture(request, pk, False)

            mix.picture_file = request.FILES['picfile']
            mix.save()

            response['file'] = str(mix.picture_file.url)
        else:
            return jsonResponse(False, {'error': form.errors})

    else:
        return jsonResponse(False, {'error': 'No post.'})

    return jsonResponse(True, response)


@login_required
def delete_picture(request, pk, return_http=True):
    try:
        mix = Mix.objects.get(pk=pk, is_published=False)

    except mix.DoesNotExist:
        if (return_http):
            return jsonResponse(False, {'error': 'No mix'})
        else:
            return False

    if (mix.user != request.user):

mixswap/mixes/templates/mixes/mix.html
{% extends 'base.html' %}
{% block page_class %}mix-page{% endblock %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block content %}
<div id="bgDropper"></div>

<div id="contentWrapper">
    <div id="mix">

        <header>
            <h1 id="mixTitle" class="mix-title"></h1>
            <span id="mixUsername" class="mix-user"></span>
            <a id="downloadMixLink" class="download-mix-link" href="{% url 'mixes:download_mix' mix.pk %}">Download</a>
            <a href="javascript:;" id="unpublishMixLink" class="unpublish-mix-link">Unpublish</a>
            <a href="javascript:;" id="publishMixLink" class="publish-mix-link">Publish</a>
            <a href="{% url 'home:home' %}" class="home-link">Home</a>
            <br class="clear unpublish-only">
        </header>
        
        <nav>
        </nav>
        
        <section id="audioPlayer">
            <div id="jquery_jplayer_1" class="jp-jplayer"></div>
            <div id="jquery_jplayer_2" class="jp-jplayer"></div>
            <div id="jp_container_1" class="jp-audio">
            <div class="jp-type-single">
              <div class="jp-gui jp-interface">
                <ul class="jp-controls">
                  <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                  <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                  <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                  <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                  <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                  <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                </ul>
                <div class="jp-progress">
                  <div class="jp-seek-bar">
                    <div class="jp-play-bar"></div>
                  </div>
                </div>
                <div class="jp-volume-bar">
                  <div class="jp-volume-bar-value"></div>
                </div>
                <div class="jp-time-holder">
                  <div class="jp-current-time"></div>
                </div>
              </div>
              <div class="jp-title"></div>
              <div class="jp-no-solution">
                <span>Update Required</span>
                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
              </div>
            </div>
            </div>
            <div id="jp_container_2" class="jp-audio"></div>
        </section>
        
        <section id="mixList" class="mix-list">
            <ul id="songList" class="song-list"></ul>
        </section>
        
        <section id="addSongBlock" class="add-song-block">
        	<h1>Add songs</h1>
            <form id="uploadSongForm" action="{% url 'mixes:upload_song' mix.pk %}" enctype="multipart/form-data" method="POST">
                <div id="songUploader">There's a problem, this isn't going to work.</div>
            </form>
        </section>
    </div>
    
    
    <section id="publishMixBlock" class="publish-mix-block">
        
    </section>
    
    <section id="comments" class="comments-block">
        <div class="add-comment-block">
        	<textarea id="txtAddComment" rows="3" cols="40"></textarea>
            <button id="btnAddComment">Add</button>
        </div>
        <div id="commentsList" class="comments-list"></div>
    </section>
    
</div>

<section class="change-bg-block">
    <span class="title">Change background picture </span>
    <span class="instructions">Drag picture onto background,<br>or click "add"</span>
    
    <form id="uploadPictureForm" action="{% url 'mixes:upload_picture' mix.pk %}" enctype="multipart/form-data" method="POST">
        <div id="picUploader">There's a problem, this isn't going to work.</div>
    </form>
    <a id="removeBG" class="delete-link" href="javascript:;">remove current picture</a>
</section>

<footer>
</footer>

<section id="templates" style="display:none;">
	<ul>
    <li id="tmpSongItem" class="song-item">        
        <input id="chkFavourite" name="chkFavourite" class="favourite-checkbox" title="Favourite Track" type="checkbox" />
        <div class="song-wrapper">
            <span class="song-order"></span>
            <span class="song-title"></span><br><span class="song-artist"></span>
            <div class="total-favourite"></div>
        </div>
        <a class="song-delete" href="javascript:;">x</a>
    </li>
    </ul>
    
    <div id="tmpCommentItem" class="comment-item">
        <span class="text"></span>
    	<span class="username"></span> <time class="date"></time>
    </div>
    
   <iframe id="iUpload" name="iUpload" src="#" style="display:none;visibility:hidden;width:0;height:0;"></iframe> 

</section>
{% endblock %}

{% block scripts %}
<script>

    $(document).ready(function() {
        App.init({
            page: 'mix',
            id: {{ mix.id }}, 
            title: '{{ mix.title }}',
            username: '{{ mix.user.first_name }}',
            currentUsername: '{{ user.first_name }}',
            isUserMix: {% if is_user_mix %}true{% else %}false{% endif %}, 
            isPublished: {% if mix.is_published %}true{% else %}false{% endif %}, 
            pictureFile: '{% if mix.picture_file %}{{ mix.picture_file.url }}{% else %}{% endif %}',
            songs: [
                {% for mix_song in mix_songs.all %}
                    {% if not forloop.first %}, {% endif %}
                    { id: {{ mix_song.song.id }}, mixId: {{ mix_song.mix.id }}, artist: "{{ mix_song.song.artist }}", title: "{{ mix_song.song.title }}", songOrder: {{ mix_song.song_order }}, songFile: "{{ mix_song.song.song_file.url }}", isUserFav: {% if user in mix_song.favourites.all %}true{% else %}false{% endif %}, totalFav: {{ mix_song.favourites.all|length }} }  
                {% endfor %}
            ]
        });
    });

</script>

{% endblock %}

mixswap/mixes/templates/mixes/top-favs.html
Top Favs